In [15]:
# Jupyter Notebook中的代码
import numpy as np

x = np.arange(15).reshape(3, 5)
x.shape
# (3, 5)

(3, 5)

In [5]:
#导入numpy库 

import numpy as np


#创建一个3行1列的矩阵
a = np.array([1, 2, 3])
#输出矩阵的维度，结果为（3，）
print(a.shape)
#选择矩阵的对应元素，在此处就是第一维度，第二维度，第三维度
print(a[0], a[1], a[2])
#创建一个2行3列的矩阵
b = np.array([[1,2,3],[4,5,6]])
#输出对应元素
print(b[0, 0], b[0, 1], b[1, 0])
#创建一个2*2的0矩阵，即元素全部为0
a = np.zeros((2,2))
#创建一个全部元素为1的矩阵
b = np.ones((1,2))
#创建一个元素全部为n的2*2矩阵
n=5
c = np.full((2,2), n)
#创建一个随机矩阵，即其中的元素值全部#为随机数
e = np.random.random((2,2))

(3,)
1 2 3
1 2 4


In [7]:
import numpy
#获取a矩阵的前两行，1到3列的数据
a = np.array([[1,2], [3, 4], [5, 6]])
b = a[:2, 1:3]
#将0行0列置为77
b[0, 0] = 77
#将a的第1行赋给row_r1
row_r1 = a[1, :]
#依然是将a的第1行赋给row_r2，但是不同的是，同样是1行但此时row_r2有两个维度
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape) # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape) # Prints "[[5 6 7 8]] (1, 4)"
#注意此时a虽然是两行三列的矩阵，但它其实是个3维矩阵，他只是三个维度中的一个
print(a[0])#Prints "[[1,2], [3, 4], [5, 6]]"
print(np.array([a[0, 0], a[1, 1], a[2, 0]])) # Prints "[1 4 5]"
b = np.array([0,1,1])
print(np.arange(2))
#将b当做索引，从a中取出对应值
print(a[np.arange(3), b]) # Prints "[ 1 6 7 11]"Prints[1,4,6]

[3 4] (2,)
[[3 4]] (1, 2)
[ 1 77]
[1 4 5]
[0 1]
[1 4 6]


In [8]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx) # Prints "[[False False]
# [ True True]
# [ True True]]"
print(a[bool_idx]) # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [10]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
#对应相乘做和，1*9+2*10=29
print(np.dot(x, v)) #print"[29 67]"
#对应直接做和，axis=0时代表行，axis=1时对应列
print(np.sum(x)) #  prints "10"
print(np.sum(x, axis=0)) #  prints "[4 6]"
print(np.sum(x, axis=1)) #  prints "[3 7]"

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) # 生成一个维度完全和矩阵x相同的空矩阵
for i in range(4):
    y[i, :] = x[i, :] + v

[29 67]
10
[4 6]
[3 7]


In [12]:
#下面这些算法都是按照对应维度去进行计算的，因此要求必须两个运算矩阵的维度必须完全相同I
import numpy as np
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
#加法
print(x + y)
print(np.add(x, y))
#减法
print(x - y)
print(np.subtract(x, y))
#乘法
print(x * y)
#除法
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))
#开方
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [13]:
v = np.array([1,2,3]) # v has shape (3,)
w = np.array([4,5]) # w has shape (2,)
#将v矩阵重置为3行1列的矩阵（）原本为1行3列）然后与w矩阵相乘
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [14]:
import numpy as np
arr = np.arange(10)
print(arr[5:])
# 输出：array([5, 6, 7, 8, 9])
print(arr[::2])
# 输出：array([0, 2, 4, 6, 8])
print(arr[::-1])
# 输出：array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

[5 6 7 8 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [18]:
import numpy as np

arr = np.arange(15).reshape(3, 5)
print(arr[:2, :3])
# 输出：array([[0, 1, 2],
#               [5, 6, 7]])
print(arr[:2])
# 输出：array([[0, 1, 2, 3, 4],
#               [5, 6, 7, 8, 9]])
print(arr[:2, ::2])
# 输出：array([[0, 2, 4],
#               [5, 7, 9]])
print(arr[::-1, ::-1])
# 输出：array([[14, 13, 12, 11, 10],
#               [ 9,  8,  7,  6,  5],
#               [ 4,  3,  2,  1,  0]])

[[0 1 2]
 [5 6 7]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 2 4]
 [5 7 9]]
[[14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


In [19]:
arr = np.arange(15).reshape(3, 5)
subarr = arr[:2, :3]
print(subarr)
# 输出：array([[0, 1, 2],
#               [5, 6, 7]])
subarr[0, 0] = 100
print(arr)
# 输出：array([[100,   1,   2,   3,   4],
#       　　　   [  5,   6,   7,   8,   9],
#       　　     [ 10,  11,  12,  13,  14]])
arr[0, 0] = 20
print(subarr)
# 输出：array([[20,  1,  2],
#               [ 5,  6,  7]])

[[0 1 2]
 [5 6 7]]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]
[[20  1  2]
 [ 5  6  7]]
